### ISSUE TITLE
Google Analytics table data are not shown

### ISSUE THREAD

**Issue by Nandhini-Kumaresan** [datainsider-co/rocket-bi#100]
updated **docker-compose.yml** with the most recent version. The total number of inserted rows is displayed along with the job's successful sync, but the **data is not displayed on the table**.

![image](https://github.com/datainsider-co/rocket-bi/assets/148965262/54392de2-4ed9-427b-9963-353a04008b63)

For your reference attached the table data screenshot.
![image](https://github.com/datainsider-co/rocket-bi/assets/148965262/d7072747-a510-4ad0-b126-5933e32d6380)

**Comment by tvc12** [comment]
Hi @Nandhini-Kumaresan ,
Can you create a new job, synchronize it with the new database, and check it again?

By the way, can you please check the log in the folder named rocket-bi-server and print it here?

**Comment by Nandhini-Kumaresan** [comment]
Hi @tvc12 ,
Created a new job and checked with the new database still same issue continues.
Also, below is the error from the log named **rocket-bi-server.log**.

```
I/O error Pipe closed for process: [tail, -n, +2, /app/./tmp/clickhouse/0/test_database/__di_tmp_site_content_1701409776609/1701409785863.json]
java.io.IOException: Pipe closed
	at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:260)
	at java.io.PipedInputStream.awaitSpace(PipedInputStream.java:268)
	at java.io.PipedInputStream.receive(PipedInputStream.java:231)
	at java.io.PipedOutputStream.write(PipedOutputStream.java:149)
	at scala.sys.process.BasicIO$.loop$1(BasicIO.scala:240)
	at scala.sys.process.BasicIO$.transferFullyImpl(BasicIO.scala:246)
	at scala.sys.process.BasicIO$.transferFully(BasicIO.scala:227)
	at scala.sys.process.ProcessImpl$PipeThread.runloop(ProcessImpl.scala:170)
	at scala.sys.process.ProcessImpl$PipeSource.run(ProcessImpl.scala:188)
I/O error Pipe closed for process: [tail, -n, +2, /app/./tmp/clickhouse/0/test_database/__di_tmp_event_1701409796627/1701409804060.json]
java.io.IOException: Pipe closed
	at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:260)
	at java.io.PipedInputStream.awaitSpace(PipedInputStream.java:268)
	at java.io.PipedInputStream.receive(PipedInputStream.java:231)
	at java.io.PipedOutputStream.write(PipedOutputStream.java:149)
	at scala.sys.process.BasicIO$.loop$1(BasicIO.scala:240)
	at scala.sys.process.BasicIO$.transferFullyImpl(BasicIO.scala:246)
	at scala.sys.process.BasicIO$.transferFully(BasicIO.scala:227)
	at scala.sys.process.ProcessImpl$PipeThread.runloop(ProcessImpl.scala:170)
	at scala.sys.process.ProcessImpl$PipeSource.run(ProcessImpl.scala:188)
```

**Comment by tvc12** [comment]
Hi @Nandhini-Kumaresan ,
Are you use clickhouse for data warehouse?
